### ISSUE TITLE
Create a stepper component

### ISSUE THREAD

**Issue by rahuljh** [sha-el/sha-el-design#26]
Add a stepper component which can be used for creating form wizards.

### Ref
https://material-ui.com/components/steppers/
https://www.telerik.com/kendo-react-ui/components/layout/stepper/
https://ant.design/components/steps/

**Comment by suman-kr** [comment]
[Multi-step form React](https://medium.com/javascript-in-plain-english/how-to-create-a-multi-step-form-with-react-hooks-53a85efdff62)
