### ISSUE TITLE
Flexbox Table

### ISSUE THREAD

**Issue by suman-kr** [sha-el/sha-el-design#9]
Create a flexbox table which is responsive for mobile devices.

**Comment by anitnilay20** [comment]
### Ref
* [Features from antd](https://ant.design/components/table/#components-table-demo-dynamic-settings)
* https://css-tricks.com/accessible-simple-responsive-tables/
* [codepen example](https://codepen.io/Thiru/pen/bmxvZK?__cf_chl_jschl_tk__=96ce8b696c262aeb7e47c3c1f649a4a28d19d4a5-1600931465-0-AVqTkPJRCwFSK8S1mFMXT3Vrd0VWQSE_eTAVQsYP4cGdcAsdJhtkM6jKeJrkH9HemlpA7QliHvhwYjnskNC_1HO8w6HJPqGT5wJ-CViqadbkMLu47LjxNssmkV0MFQAOarxoxoMZVRFHgllzqdzl3AGgLsj3keyu7hI9uHnzImjyiCpx48V9l8As9WNxEAqPdHplUxY9wRZWGZuqtfUAR-Dvy5HrGh3052Z4fEe9pgb6cxqbho2TDJxOzXyNCM6JRiQm1kd3Z0yBxE2U-HPweaocX5gAu8XtQS5m5ga1YtNrZ3vrHKW3b2n-BZQWlxQddD5kbQUEFGxUeqb3qH5NHZT7MOqHhTFOoCd2QdOMo1ga)
* [codepen react example](https://codepen.io/jonstuebe/pen/XgKpzq?__cf_chl_jschl_tk__=cffdee933de5f4e0cd3b6f16a3b12e874de180f6-1596649963-0-AThkFT5_fLVlZ0QXhRZqbqz0ZlRZhDMjQvTZhTC7HyywSlJCf3-Rugr2bi7GX4yUhZwOi2dktxHTNI3AgdWQzGk891SNoxnqsULGCGmcU_makFHd79_vzE8R3YJJBeaD2WofPZlGk7jkXF2R_crpGQAy0QlvwykuP-lYZIuzsk6Qt647qK6GfkUQUNCJUwxKTW3mL6PcMSskaxDQRrJxLaj6DyXjE8FkMlwDUWLxlhJRW-gFBSlnEiFvScPGxKKi7oSoK4MI5_dLDrvteNgnzz5ElC_BGD5n-oe59SEUBZRSHML45faIfHAtF7HqqMKkyAL7LK5Noc2FqAZ-r2lojPmeda97sAd-v-ci_S26AO2k
)
